/**
 * The TypeScript comparison chart must reproduce the canonical Python renderer
 * byte for byte, for every metric, every ordered school pair and several year
 * windows (fixture generated by tools/build_chart_fixtures.py; each case is
 * pinned by SHA-256, and every 250th case carries the full SVG for diagnosis).
 */
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { comparisonChart } from '../../src/lib/chart';

interface Fixture {
  metrics: { id: string; label: string; unit: 'percent' | 'count'; points: { schoolId: string; schoolName: string; year: number; value: number; status: string }[] }[];
  cases: { metric: string; first: string; second: string; yearFrom: number; yearTo: number; sha256: string; svg?: string }[];
}

const fixture = JSON.parse(readFileSync(new URL('../fixtures/comparison-charts.json', import.meta.url), 'utf8')) as Fixture;
const sha = (text: string) => createHash('sha256').update(text, 'utf8').digest('hex');

describe('comparison chart parity with the Python renderer', () => {
  it('covers every metric and hundreds of school pairs and windows', () => {
    expect(fixture.metrics.length).toBeGreaterThanOrEqual(11);
    expect(fixture.cases.length).toBeGreaterThan(1000);
    expect(fixture.cases.filter((item) => item.svg).length).toBeGreaterThan(5);
  });

  it('renders every fixture case identically', () => {
    const mismatches: string[] = [];
    for (const item of fixture.cases) {
      const metric = fixture.metrics.find((entry) => entry.id === item.metric)!;
      const rendered = comparisonChart(metric, item.first, item.second, item.yearFrom, item.yearTo);
      if (item.svg) expect(rendered, `${item.metric} ${item.first}/${item.second} ${item.yearFrom}-${item.yearTo}`).toBe(item.svg);
      if (sha(rendered) !== item.sha256) mismatches.push(`${item.metric} ${item.first}/${item.second} ${item.yearFrom}-${item.yearTo}`);
    }
    expect(mismatches).toEqual([]);
  });
});
