/**
 * The TypeScript comparison panel must reproduce the canonical Python renderer
 * byte for byte, for every metric, every ordered school pair, several year
 * windows and both layouts (fixture generated by tools/build_chart_fixtures.py;
 * each case is pinned by SHA-256, and every 500th case carries the full SVG).
 */
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { COMPARISON_DESKTOP, COMPARISON_MOBILE, EXCEPTIONAL_YEARS, comparisonPanel } from '../../src/lib/panel';

interface Fixture {
  schools: { id: string; name: string }[];
  metrics: { id: string; label: string; unit: 'percent' | 'count'; domain: string; points: { schoolId: string; schoolName: string; year: number; value: number; status: string }[] }[];
  cases: { metric: string; first: string; second: string; yearFrom: number; yearTo: number; layout: 'desktop' | 'mobile'; sha256: string; svg?: string }[];
}

const fixture = JSON.parse(readFileSync(new URL('../fixtures/comparison-charts.json', import.meta.url), 'utf8')) as Fixture;
const sha = (text: string) => createHash('sha256').update(text, 'utf8').digest('hex');
const names = Object.fromEntries(fixture.schools.map((school) => [school.id, school.name]));

describe('comparison panel parity with the Python renderer', () => {
  it('covers every metric, hundreds of school pairs and windows, and both layouts', () => {
    expect(fixture.metrics.length).toBeGreaterThanOrEqual(11);
    expect(fixture.cases.length).toBeGreaterThan(2000);
    expect(fixture.cases.filter((item) => item.svg).length).toBeGreaterThan(5);
    expect(new Set(fixture.cases.map((item) => item.layout)).size).toBe(2);
  });

  it('renders every fixture case identically', () => {
    const mismatches: string[] = [];
    for (const item of fixture.cases) {
      const metric = fixture.metrics.find((entry) => entry.id === item.metric)!;
      const layout = item.layout === 'mobile' ? COMPARISON_MOBILE : COMPARISON_DESKTOP;
      const markers = metric.domain === 'results' ? [EXCEPTIONAL_YEARS] : [];
      const rendered = comparisonPanel(metric, item.first, item.second, item.yearFrom, item.yearTo, layout, { names, markers });
      if (item.svg) expect(rendered, `${item.metric} ${item.first}/${item.second} ${item.yearFrom}-${item.yearTo} ${item.layout}`).toBe(item.svg);
      if (sha(rendered) !== item.sha256) mismatches.push(`${item.metric} ${item.first}/${item.second} ${item.yearFrom}-${item.yearTo} ${item.layout}`);
    }
    expect(mismatches).toEqual([]);
  });
});
