[theme]
base = "light"
primaryColor = "#125c58"
backgroundColor = "#f3f1eb"
secondaryBackgroundColor = "#ebe7dd"
textColor = "#20231f"

[server]
enableStaticServing = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = true
